-- Cloudflare D1 Migration & Seed: 0001_pseo_entities.sql
-- Generated automatically by scripts/seed_indonesia_pseo_engine.ts

CREATE TABLE IF NOT EXISTS pseo_entities (
  slug TEXT NOT NULL,
  category TEXT NOT NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  target_keyword TEXT NOT NULL,
  area_served TEXT NOT NULL,
  wikidata_uri TEXT NOT NULL,
  bps_code TEXT,
  is_anchor INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (category, slug)
);

CREATE INDEX IF NOT EXISTS idx_pseo_category ON pseo_entities(category);
CREATE INDEX IF NOT EXISTS idx_pseo_area ON pseo_entities(area_served);
CREATE INDEX IF NOT EXISTS idx_pseo_is_anchor ON pseo_entities(is_anchor);

-- Batch INSERT Statements
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('jakarta-pusat', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Jakarta Pusat', 'jasa pembuatan web jakarta pusat', 'Jakarta Pusat', 'https://www.wikidata.org/wiki/Q10116', '3171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('jakarta-selatan', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Jakarta Selatan', 'jasa pembuatan web jakarta selatan', 'Jakarta Selatan', 'https://www.wikidata.org/wiki/Q10119', '3174', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('surabaya', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Surabaya', 'jasa pembuatan web surabaya', 'Surabaya', 'https://www.wikidata.org/wiki/Q11462', '3578', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bandung', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Bandung', 'jasa pembuatan web bandung', 'Bandung', 'https://www.wikidata.org/wiki/Q10389', '3273', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('semarang', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Semarang', 'jasa pembuatan web semarang', 'Semarang', 'https://www.wikidata.org/wiki/Q11468', '3374', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('yogyakarta', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Yogyakarta', 'jasa pembuatan web yogyakarta', 'Yogyakarta', 'https://www.wikidata.org/wiki/Q42735', '3471', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('malang', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Malang', 'jasa pembuatan web malang', 'Malang', 'https://www.wikidata.org/wiki/Q11449', '3573', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('surakarta', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Surakarta (Solo)', 'jasa pembuatan web surakarta (solo)', 'Surakarta (Solo)', 'https://www.wikidata.org/wiki/Q11457', '3372', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bekasi', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Bekasi', 'jasa pembuatan web bekasi', 'Bekasi', 'https://www.wikidata.org/wiki/Q10123', '3275', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('tangerang', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Tangerang', 'jasa pembuatan web tangerang', 'Tangerang', 'https://www.wikidata.org/wiki/Q10128', '3671', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('depok', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Depok', 'jasa pembuatan web depok', 'Depok', 'https://www.wikidata.org/wiki/Q10124', '3276', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bogor', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Bogor', 'jasa pembuatan web bogor', 'Bogor', 'https://www.wikidata.org/wiki/Q10393', '3271', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('cirebon', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Cirebon', 'jasa pembuatan web cirebon', 'Cirebon', 'https://www.wikidata.org/wiki/Q10395', '3274', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('jember', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Jember', 'jasa pembuatan web jember', 'Jember', 'https://www.wikidata.org/wiki/Q11442', '3509', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('medan', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Medan', 'jasa pembuatan web medan', 'Medan', 'https://www.wikidata.org/wiki/Q5972', '1271', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('palembang', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Palembang', 'jasa pembuatan web palembang', 'Palembang', 'https://www.wikidata.org/wiki/Q8412', '1671', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('batam', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Batam', 'jasa pembuatan web batam', 'Batam', 'https://www.wikidata.org/wiki/Q10114', '2171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('pekanbaru', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Pekanbaru', 'jasa pembuatan web pekanbaru', 'Pekanbaru', 'https://www.wikidata.org/wiki/Q7433', '1471', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('padang', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Padang', 'jasa pembuatan web padang', 'Padang', 'https://www.wikidata.org/wiki/Q7253', '1371', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bandar-lampung', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Bandar Lampung', 'jasa pembuatan web bandar lampung', 'Bandar Lampung', 'https://www.wikidata.org/wiki/Q10113', '1871', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('pontianak', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Pontianak', 'jasa pembuatan web pontianak', 'Pontianak', 'https://www.wikidata.org/wiki/Q14168', '6171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('balikpapan', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Balikpapan', 'jasa pembuatan web balikpapan', 'Balikpapan', 'https://www.wikidata.org/wiki/Q14175', '6471', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('samarinda', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Samarinda', 'jasa pembuatan web samarinda', 'Samarinda', 'https://www.wikidata.org/wiki/Q14178', '6472', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('banjarmasin', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Banjarmasin', 'jasa pembuatan web banjarmasin', 'Banjarmasin', 'https://www.wikidata.org/wiki/Q14170', '6371', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('makassar', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Makassar', 'jasa pembuatan web makassar', 'Makassar', 'https://www.wikidata.org/wiki/Q14188', '7371', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('manado', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Manado', 'jasa pembuatan web manado', 'Manado', 'https://www.wikidata.org/wiki/Q14183', '7171', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('denpasar', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Denpasar', 'jasa pembuatan web denpasar', 'Denpasar', 'https://www.wikidata.org/wiki/Q11505', '5171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('mataram', 'web', 'local', 'Jasa Pembuatan Web Modern & Cepat di Mataram', 'jasa pembuatan web mataram', 'Mataram', 'https://www.wikidata.org/wiki/Q14162', '5271', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('jakarta-pusat', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Jakarta Pusat', 'konsultan seo jakarta pusat', 'Jakarta Pusat', 'https://www.wikidata.org/wiki/Q10116', '3171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('jakarta-selatan', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Jakarta Selatan', 'konsultan seo jakarta selatan', 'Jakarta Selatan', 'https://www.wikidata.org/wiki/Q10119', '3174', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('surabaya', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Surabaya', 'konsultan seo surabaya', 'Surabaya', 'https://www.wikidata.org/wiki/Q11462', '3578', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bandung', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Bandung', 'konsultan seo bandung', 'Bandung', 'https://www.wikidata.org/wiki/Q10389', '3273', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('semarang', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Semarang', 'konsultan seo semarang', 'Semarang', 'https://www.wikidata.org/wiki/Q11468', '3374', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('yogyakarta', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Yogyakarta', 'konsultan seo yogyakarta', 'Yogyakarta', 'https://www.wikidata.org/wiki/Q42735', '3471', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('malang', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Malang', 'konsultan seo malang', 'Malang', 'https://www.wikidata.org/wiki/Q11449', '3573', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('surakarta', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Surakarta (Solo)', 'konsultan seo surakarta (solo)', 'Surakarta (Solo)', 'https://www.wikidata.org/wiki/Q11457', '3372', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bekasi', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Bekasi', 'konsultan seo bekasi', 'Bekasi', 'https://www.wikidata.org/wiki/Q10123', '3275', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('tangerang', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Tangerang', 'konsultan seo tangerang', 'Tangerang', 'https://www.wikidata.org/wiki/Q10128', '3671', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('depok', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Depok', 'konsultan seo depok', 'Depok', 'https://www.wikidata.org/wiki/Q10124', '3276', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bogor', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Bogor', 'konsultan seo bogor', 'Bogor', 'https://www.wikidata.org/wiki/Q10393', '3271', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('cirebon', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Cirebon', 'konsultan seo cirebon', 'Cirebon', 'https://www.wikidata.org/wiki/Q10395', '3274', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('jember', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Jember', 'konsultan seo jember', 'Jember', 'https://www.wikidata.org/wiki/Q11442', '3509', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('medan', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Medan', 'konsultan seo medan', 'Medan', 'https://www.wikidata.org/wiki/Q5972', '1271', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('palembang', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Palembang', 'konsultan seo palembang', 'Palembang', 'https://www.wikidata.org/wiki/Q8412', '1671', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('batam', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Batam', 'konsultan seo batam', 'Batam', 'https://www.wikidata.org/wiki/Q10114', '2171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('pekanbaru', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Pekanbaru', 'konsultan seo pekanbaru', 'Pekanbaru', 'https://www.wikidata.org/wiki/Q7433', '1471', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('padang', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Padang', 'konsultan seo padang', 'Padang', 'https://www.wikidata.org/wiki/Q7253', '1371', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('bandar-lampung', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Bandar Lampung', 'konsultan seo bandar lampung', 'Bandar Lampung', 'https://www.wikidata.org/wiki/Q10113', '1871', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('pontianak', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Pontianak', 'konsultan seo pontianak', 'Pontianak', 'https://www.wikidata.org/wiki/Q14168', '6171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('balikpapan', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Balikpapan', 'konsultan seo balikpapan', 'Balikpapan', 'https://www.wikidata.org/wiki/Q14175', '6471', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('samarinda', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Samarinda', 'konsultan seo samarinda', 'Samarinda', 'https://www.wikidata.org/wiki/Q14178', '6472', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('banjarmasin', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Banjarmasin', 'konsultan seo banjarmasin', 'Banjarmasin', 'https://www.wikidata.org/wiki/Q14170', '6371', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('makassar', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Makassar', 'konsultan seo makassar', 'Makassar', 'https://www.wikidata.org/wiki/Q14188', '7371', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('manado', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Manado', 'konsultan seo manado', 'Manado', 'https://www.wikidata.org/wiki/Q14183', '7171', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('denpasar', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Denpasar', 'konsultan seo denpasar', 'Denpasar', 'https://www.wikidata.org/wiki/Q11505', '5171', 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('mataram', 'seo', 'local', 'Konsultan Technical SEO & Strategi Konversi di Mataram', 'konsultan seo mataram', 'Mataram', 'https://www.wikidata.org/wiki/Q14162', '5271', 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-indonesia', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Indonesia (UI)', 'olah data statistik universitas indonesia', 'Universitas Indonesia (UI), Depok / Jakarta', 'https://www.wikidata.org/wiki/Q848524', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('institut-teknologi-bandung', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Institut Teknologi Bandung (ITB)', 'olah data statistik institut teknologi bandung', 'Institut Teknologi Bandung (ITB), Bandung', 'https://www.wikidata.org/wiki/Q1321456', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-gadjah-mada', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Gadjah Mada (UGM)', 'olah data statistik universitas gadjah mada', 'Universitas Gadjah Mada (UGM), Yogyakarta', 'https://www.wikidata.org/wiki/Q1145265', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-airlangga', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Airlangga (UNAIR)', 'olah data statistik universitas airlangga', 'Universitas Airlangga (UNAIR), Surabaya', 'https://www.wikidata.org/wiki/Q1151608', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('institut-teknologi-sepuluh-nopember', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Institut Teknologi Sepuluh Nopember (ITS)', 'olah data statistik institut teknologi sepuluh nopember', 'Institut Teknologi Sepuluh Nopember (ITS), Surabaya', 'https://www.wikidata.org/wiki/Q1653846', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-brawijaya', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Brawijaya (UB)', 'olah data statistik universitas brawijaya', 'Universitas Brawijaya (UB), Malang', 'https://www.wikidata.org/wiki/Q1188584', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-diponegoro', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Diponegoro (UNDIP)', 'olah data statistik universitas diponegoro', 'Universitas Diponegoro (UNDIP), Semarang', 'https://www.wikidata.org/wiki/Q1271167', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-padjadjaran', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Padjadjaran (UNPAD)', 'olah data statistik universitas padjadjaran', 'Universitas Padjadjaran (UNPAD), Bandung', 'https://www.wikidata.org/wiki/Q1187498', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-sebelas-maret', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Sebelas Maret (UNS)', 'olah data statistik universitas sebelas maret', 'Universitas Sebelas Maret (UNS), Surakarta', 'https://www.wikidata.org/wiki/Q1187499', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-sumatera-utara', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Sumatera Utara (USU)', 'olah data statistik universitas sumatera utara', 'Universitas Sumatera Utara (USU), Medan', 'https://www.wikidata.org/wiki/Q4115167', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-hasanuddin', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Hasanuddin (UNHAS)', 'olah data statistik universitas hasanuddin', 'Universitas Hasanuddin (UNHAS), Makassar', 'https://www.wikidata.org/wiki/Q1145455', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-tanjungpura', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Tanjungpura (UNTAN)', 'olah data statistik universitas tanjungpura', 'Universitas Tanjungpura (UNTAN), Pontianak', 'https://www.wikidata.org/wiki/Q7901047', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('ipb-university', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - IPB University', 'olah data statistik ipb university', 'IPB University, Bogor', 'https://www.wikidata.org/wiki/Q1653556', NULL, 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-udayana', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Udayana (UNUD)', 'olah data statistik universitas udayana', 'Universitas Udayana (UNUD), Denpasar', 'https://www.wikidata.org/wiki/Q12523297', NULL, 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-andalas', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Andalas (UNAND)', 'olah data statistik universitas andalas', 'Universitas Andalas (UNAND), Padang', 'https://www.wikidata.org/wiki/Q1187497', NULL, 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('universitas-sriwijaya', 'sinta', 'industry', 'Pendampingan Publikasi Jurnal SINTA & Olah Data Statistik - Universitas Sriwijaya (UNSRI)', 'olah data statistik universitas sriwijaya', 'Universitas Sriwijaya (UNSRI), Palembang', 'https://www.wikidata.org/wiki/Q1187500', NULL, 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('agribisnis-perkebunan', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Agribisnis & Perkebunan (KBLI 01)', 'proposal bisnis agribisnis & perkebunan', 'Nasional Indonesia (Sektor Agribisnis & Perkebunan)', 'https://www.wikidata.org/wiki/Q7411', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('yayasan-filantropi', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Yayasan & Filantropi Sosial (KBLI 94)', 'proposal bisnis yayasan & filantropi sosial', 'Nasional Indonesia (Sektor Yayasan & Filantropi Sosial)', 'https://www.wikidata.org/wiki/Q157031', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('fintech-keuangan', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Fintech & Jasa Keuangan (KBLI 64)', 'proposal bisnis fintech & jasa keuangan', 'Nasional Indonesia (Sektor Fintech & Jasa Keuangan)', 'https://www.wikidata.org/wiki/Q1358919', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('manufaktur-industri', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Manufaktur & Pengolahan (KBLI 10)', 'proposal bisnis manufaktur & pengolahan', 'Nasional Indonesia (Sektor Manufaktur & Pengolahan)', 'https://www.wikidata.org/wiki/Q187931', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('pendidikan-tinggi', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Pendidikan Tinggi & Riset (KBLI 85)', 'proposal bisnis pendidikan tinggi & riset', 'Nasional Indonesia (Sektor Pendidikan Tinggi & Riset)', 'https://www.wikidata.org/wiki/Q136558', NULL, 1);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('klinik-kesehatan', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Klinik & Layanan Kesehatan (KBLI 86)', 'proposal bisnis klinik & layanan kesehatan', 'Nasional Indonesia (Sektor Klinik & Layanan Kesehatan)', 'https://www.wikidata.org/wiki/Q16917', NULL, 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('hospitality-pariwisata', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Hospitality & Pariwisata (KBLI 55)', 'proposal bisnis hospitality & pariwisata', 'Nasional Indonesia (Sektor Hospitality & Pariwisata)', 'https://www.wikidata.org/wiki/Q746358', NULL, 0);
INSERT OR REPLACE INTO pseo_entities (slug, category, type, title, target_keyword, area_served, wikidata_uri, bps_code, is_anchor) VALUES ('logistik-ekspedisi', 'bisnis', 'industry', 'Penyusunan Proposal Bisnis, Pitch Deck & SOP Sektor Logistik & Ekspedisi B2B (KBLI 49)', 'proposal bisnis logistik & ekspedisi b2b', 'Nasional Indonesia (Sektor Logistik & Ekspedisi B2B)', 'https://www.wikidata.org/wiki/Q1028781', NULL, 0);
